/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { OmnifexVariant } from "./shared/variant.enum";
import { OmnifexAppearance } from "./shared/appearance.enum";
export { OmnifexVariant } from "./shared/variant.enum";
export { OmnifexAppearance } from "./shared/appearance.enum";
export namespace Components {
    interface OmnifexBadge {
        /**
          * @default OmnifexVariant.PRIMARY
         */
        "variant": OmnifexVariant;
    }
    interface OmnifexButton {
        /**
          * @default OmnifexAppearance.FILLED
         */
        "appearance": OmnifexAppearance;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default OmnifexVariant.PRIMARY
         */
        "variant": OmnifexVariant;
    }
    interface OmnifexCallback {
        /**
          * @default null
         */
        "error": string | null;
        /**
          * @default false
         */
        "isLoading": boolean;
    }
    interface OmnifexCard {
        /**
          * @default OmnifexAppearance.FILLED
         */
        "appearance": OmnifexAppearance;
        /**
          * @default ''
         */
        "cardTitle": string;
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default ''
         */
        "icon": string;
        /**
          * @default []
         */
        "items": string | string[];
        /**
          * @default OmnifexVariant.PRIMARY
         */
        "variant": OmnifexVariant;
    }
    interface OmnifexFooter {
        /**
          * @default ''
         */
        "framework": string;
        /**
          * @default 'Built with ❤️'
         */
        "text": string;
    }
    interface OmnifexHeader {
        /**
          * @default false
         */
        "isAuthenticated": boolean;
        /**
          * @default false
         */
        "isDark": boolean;
        /**
          * @default false
         */
        "isLoading": boolean;
        /**
          * @default '🅰️'
         */
        "logoIcon": string;
        /**
          * @default 'Omnifex'
         */
        "logoText": string;
        /**
          * @default []
         */
        "roles": string | string[];
        /**
          * @default ''
         */
        "userName": string;
    }
    interface OmnifexIdentity {
        /**
          * @default false
         */
        "isAuthenticated": boolean;
        /**
          * @default false
         */
        "isLoading": boolean;
        /**
          * @default ''
         */
        "userName": string;
    }
    interface OmnifexThemeToggle {
        /**
          * @default false
         */
        "isDark": boolean;
    }
}
export interface OmnifexButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOmnifexButtonElement;
}
export interface OmnifexCallbackCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOmnifexCallbackElement;
}
export interface OmnifexHeaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOmnifexHeaderElement;
}
export interface OmnifexIdentityCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOmnifexIdentityElement;
}
export interface OmnifexThemeToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOmnifexThemeToggleElement;
}
declare global {
    interface HTMLOmnifexBadgeElement extends Components.OmnifexBadge, HTMLStencilElement {
    }
    var HTMLOmnifexBadgeElement: {
        prototype: HTMLOmnifexBadgeElement;
        new (): HTMLOmnifexBadgeElement;
    };
    interface HTMLOmnifexButtonElementEventMap {
        "buttonClick": void;
    }
    interface HTMLOmnifexButtonElement extends Components.OmnifexButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOmnifexButtonElementEventMap>(type: K, listener: (this: HTMLOmnifexButtonElement, ev: OmnifexButtonCustomEvent<HTMLOmnifexButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOmnifexButtonElementEventMap>(type: K, listener: (this: HTMLOmnifexButtonElement, ev: OmnifexButtonCustomEvent<HTMLOmnifexButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOmnifexButtonElement: {
        prototype: HTMLOmnifexButtonElement;
        new (): HTMLOmnifexButtonElement;
    };
    interface HTMLOmnifexCallbackElementEventMap {
        "retry-click": void;
    }
    interface HTMLOmnifexCallbackElement extends Components.OmnifexCallback, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOmnifexCallbackElementEventMap>(type: K, listener: (this: HTMLOmnifexCallbackElement, ev: OmnifexCallbackCustomEvent<HTMLOmnifexCallbackElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOmnifexCallbackElementEventMap>(type: K, listener: (this: HTMLOmnifexCallbackElement, ev: OmnifexCallbackCustomEvent<HTMLOmnifexCallbackElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOmnifexCallbackElement: {
        prototype: HTMLOmnifexCallbackElement;
        new (): HTMLOmnifexCallbackElement;
    };
    interface HTMLOmnifexCardElement extends Components.OmnifexCard, HTMLStencilElement {
    }
    var HTMLOmnifexCardElement: {
        prototype: HTMLOmnifexCardElement;
        new (): HTMLOmnifexCardElement;
    };
    interface HTMLOmnifexFooterElement extends Components.OmnifexFooter, HTMLStencilElement {
    }
    var HTMLOmnifexFooterElement: {
        prototype: HTMLOmnifexFooterElement;
        new (): HTMLOmnifexFooterElement;
    };
    interface HTMLOmnifexHeaderElementEventMap {
        "login-click": void;
        "logout-click": void;
        "theme-toggle": void;
    }
    interface HTMLOmnifexHeaderElement extends Components.OmnifexHeader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOmnifexHeaderElementEventMap>(type: K, listener: (this: HTMLOmnifexHeaderElement, ev: OmnifexHeaderCustomEvent<HTMLOmnifexHeaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOmnifexHeaderElementEventMap>(type: K, listener: (this: HTMLOmnifexHeaderElement, ev: OmnifexHeaderCustomEvent<HTMLOmnifexHeaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOmnifexHeaderElement: {
        prototype: HTMLOmnifexHeaderElement;
        new (): HTMLOmnifexHeaderElement;
    };
    interface HTMLOmnifexIdentityElementEventMap {
        "login-click": void;
        "logout-click": void;
    }
    interface HTMLOmnifexIdentityElement extends Components.OmnifexIdentity, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOmnifexIdentityElementEventMap>(type: K, listener: (this: HTMLOmnifexIdentityElement, ev: OmnifexIdentityCustomEvent<HTMLOmnifexIdentityElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOmnifexIdentityElementEventMap>(type: K, listener: (this: HTMLOmnifexIdentityElement, ev: OmnifexIdentityCustomEvent<HTMLOmnifexIdentityElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOmnifexIdentityElement: {
        prototype: HTMLOmnifexIdentityElement;
        new (): HTMLOmnifexIdentityElement;
    };
    interface HTMLOmnifexThemeToggleElementEventMap {
        "toggle-click": void;
    }
    interface HTMLOmnifexThemeToggleElement extends Components.OmnifexThemeToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOmnifexThemeToggleElementEventMap>(type: K, listener: (this: HTMLOmnifexThemeToggleElement, ev: OmnifexThemeToggleCustomEvent<HTMLOmnifexThemeToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOmnifexThemeToggleElementEventMap>(type: K, listener: (this: HTMLOmnifexThemeToggleElement, ev: OmnifexThemeToggleCustomEvent<HTMLOmnifexThemeToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOmnifexThemeToggleElement: {
        prototype: HTMLOmnifexThemeToggleElement;
        new (): HTMLOmnifexThemeToggleElement;
    };
    interface HTMLElementTagNameMap {
        "omnifex-badge": HTMLOmnifexBadgeElement;
        "omnifex-button": HTMLOmnifexButtonElement;
        "omnifex-callback": HTMLOmnifexCallbackElement;
        "omnifex-card": HTMLOmnifexCardElement;
        "omnifex-footer": HTMLOmnifexFooterElement;
        "omnifex-header": HTMLOmnifexHeaderElement;
        "omnifex-identity": HTMLOmnifexIdentityElement;
        "omnifex-theme-toggle": HTMLOmnifexThemeToggleElement;
    }
}
declare namespace LocalJSX {
    interface OmnifexBadge {
        /**
          * @default OmnifexVariant.PRIMARY
         */
        "variant"?: OmnifexVariant;
    }
    interface OmnifexButton {
        /**
          * @default OmnifexAppearance.FILLED
         */
        "appearance"?: OmnifexAppearance;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onButtonClick"?: (event: OmnifexButtonCustomEvent<void>) => void;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default OmnifexVariant.PRIMARY
         */
        "variant"?: OmnifexVariant;
    }
    interface OmnifexCallback {
        /**
          * @default null
         */
        "error"?: string | null;
        /**
          * @default false
         */
        "isLoading"?: boolean;
        "onRetry-click"?: (event: OmnifexCallbackCustomEvent<void>) => void;
    }
    interface OmnifexCard {
        /**
          * @default OmnifexAppearance.FILLED
         */
        "appearance"?: OmnifexAppearance;
        /**
          * @default ''
         */
        "cardTitle"?: string;
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default ''
         */
        "icon"?: string;
        /**
          * @default []
         */
        "items"?: string | string[];
        /**
          * @default OmnifexVariant.PRIMARY
         */
        "variant"?: OmnifexVariant;
    }
    interface OmnifexFooter {
        /**
          * @default ''
         */
        "framework"?: string;
        /**
          * @default 'Built with ❤️'
         */
        "text"?: string;
    }
    interface OmnifexHeader {
        /**
          * @default false
         */
        "isAuthenticated"?: boolean;
        /**
          * @default false
         */
        "isDark"?: boolean;
        /**
          * @default false
         */
        "isLoading"?: boolean;
        /**
          * @default '🅰️'
         */
        "logoIcon"?: string;
        /**
          * @default 'Omnifex'
         */
        "logoText"?: string;
        "onLogin-click"?: (event: OmnifexHeaderCustomEvent<void>) => void;
        "onLogout-click"?: (event: OmnifexHeaderCustomEvent<void>) => void;
        "onTheme-toggle"?: (event: OmnifexHeaderCustomEvent<void>) => void;
        /**
          * @default []
         */
        "roles"?: string | string[];
        /**
          * @default ''
         */
        "userName"?: string;
    }
    interface OmnifexIdentity {
        /**
          * @default false
         */
        "isAuthenticated"?: boolean;
        /**
          * @default false
         */
        "isLoading"?: boolean;
        "onLogin-click"?: (event: OmnifexIdentityCustomEvent<void>) => void;
        "onLogout-click"?: (event: OmnifexIdentityCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "userName"?: string;
    }
    interface OmnifexThemeToggle {
        /**
          * @default false
         */
        "isDark"?: boolean;
        "onToggle-click"?: (event: OmnifexThemeToggleCustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "omnifex-badge": OmnifexBadge;
        "omnifex-button": OmnifexButton;
        "omnifex-callback": OmnifexCallback;
        "omnifex-card": OmnifexCard;
        "omnifex-footer": OmnifexFooter;
        "omnifex-header": OmnifexHeader;
        "omnifex-identity": OmnifexIdentity;
        "omnifex-theme-toggle": OmnifexThemeToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "omnifex-badge": LocalJSX.OmnifexBadge & JSXBase.HTMLAttributes<HTMLOmnifexBadgeElement>;
            "omnifex-button": LocalJSX.OmnifexButton & JSXBase.HTMLAttributes<HTMLOmnifexButtonElement>;
            "omnifex-callback": LocalJSX.OmnifexCallback & JSXBase.HTMLAttributes<HTMLOmnifexCallbackElement>;
            "omnifex-card": LocalJSX.OmnifexCard & JSXBase.HTMLAttributes<HTMLOmnifexCardElement>;
            "omnifex-footer": LocalJSX.OmnifexFooter & JSXBase.HTMLAttributes<HTMLOmnifexFooterElement>;
            "omnifex-header": LocalJSX.OmnifexHeader & JSXBase.HTMLAttributes<HTMLOmnifexHeaderElement>;
            "omnifex-identity": LocalJSX.OmnifexIdentity & JSXBase.HTMLAttributes<HTMLOmnifexIdentityElement>;
            "omnifex-theme-toggle": LocalJSX.OmnifexThemeToggle & JSXBase.HTMLAttributes<HTMLOmnifexThemeToggleElement>;
        }
    }
}
